site_name: Geocodes Metadata
#theme: 'material'
#theme: 'mkdocs'
nav:
  - Metadata Profile: geocodesSearchProfile.md
  - Collections Profile: collections-ro-crate.md
  - MetadataPublicationOnTheWeb.md
