name: Generate xml sitemap

on:
  push:
    branches-ignore: [ 'gh-pages'  ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
#  the original sitemap, at metadata/Dataset root
    - name: Generate the dataset allgood sitemap
      id: sitemapdatasetallgood
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://raw.githubusercontent.com/earthcube/GeoCODES-Metadata/main/metadata/Dataset/allgood
        path-to-root: metadata/Dataset/allgood
        sitemap-path:  metadata/Dataset/
        include-pdf: false
        additional-extensions: json jsonld
    - name: Output dataset allgood stats
      run: |
        echo "sitemap-path = ${{ steps.sitemapdatasetallgood.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemapdatasetallgood.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemapdatasetallgood.outputs.excluded-count }}"
#
    - name: Generate the dataset json sitemap
      id: sitemapdatasetjson
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://raw.githubusercontent.com/earthcube/GeoCODES-Metadata/main/metadata/Dataset/json
        path-to-root: metadata/Dataset/json
        include-pdf: false
        additional-extensions: json jsonld
    - name: Output dataset  json stats
      run: |
        echo "sitemap-path = ${{ steps.sitemapdatasetjson.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemapdatasetjson.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemapdatasetjson.outputs.excluded-count }}"
#
    - name: Generate the dataset actualdata sitemap
      id: sitemapdatasetactualdata
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://raw.githubusercontent.com/earthcube/GeoCODES-Metadata/main/metadata/Dataset/actualdata
        path-to-root: metadata/Dataset/actualdata
        include-pdf: false
        additional-extensions: json jsonld
    - name: Output dataset  json stats
      run: |
        echo "sitemap-path = ${{ steps.sitemapdatasetactualdata.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemapdatasetactualdata.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemapdatasetactualdata.outputs.excluded-count }}"
#
    - name: Generate the development sitemap
      id: sitemapdevelopment
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://raw.githubusercontent.com/earthcube/GeoCODES-Metadata/main/metadata/development/
        path-to-root: metadata/development
        include-pdf: false
        additional-extensions: json jsonld
    - name: Output development stats
      run: |
        echo "sitemap-path = ${{ steps.sitemapdevelopment.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemapdevelopment.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemapdevelopment.outputs.excluded-count }}"- name: Deploy
    - name: Generate the otherResources sitemap
      id: sitemapotherResources
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://raw.githubusercontent.com/earthcube/GeoCODES-Metadata/main/metadata/otherResources/
        path-to-root: metadata/OtherResources/
        include-pdf: false
        additional-extensions: json jsonld
    - name: Output otherResources stats
      run: |
        echo "sitemap-path = ${{ steps.sitemapotherResources.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemapotherResources.outputs.url-count }}"
    - name: push to gh pages
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        branch: gh-pages
        folder: .

