name: Validate json files with dataset schema

on:
  push:
    branches-ignore: [ 'gh-pages' ]

jobs:
  validate-json-allgood:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 4
    - uses: walbo/validate-json@v1.1.0
      name: schema validate dataset json
      with:
        files: metadata/Dataset/allgood/**/*.json

        # optional, defaults to `$schema` in your JSON file
        schema: schemas/GeoCodes-DatasetSchema.json
        schema-version: draft-07
        print-valid-files: true
        strict: false # default is true
  validate-json-everything:
    runs-on: ubuntu-latest

    steps:
    - uses: walbo/validate-json@v1.1.0
      name: schema validate dataset json
      with:
        files: metadata/Dataset/actualdata/**/*.json,metadata/Dataset/json/**/*.json

        # optional, defaults to `$schema` in your JSON file
        schema: schemas/GeoCodes-DatasetSchema.json
        schema-version: draft-07
        print-valid-files: true
        strict: false # default is true

