name: Validate json files with dataset schema

on:
  push:
    branches-ignore: [ 'gh-pages' ]

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 4
    - uses: dsanders11/json-schema-validate-action@v1.4.0
      name: schema validate dataset json
      with:
        files: metadata/Dataset/allgood/**/*.json

        # optional, defaults to `$schema` in your JSON file
        schema: schemas/GeoCodes-DatasetSchema.json
        schema-version: draft-07
        print-valid-files: true
        all-errors: truee
        fail-on-invalid: false


