name: Validate json files

on:
  push:
    branches: [ main ]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    name: validate json with schema

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 4

    - name: Validate dataset json files
      uses: mheap/frontmatter-json-schema-action@main
      with:
        paths: 'metadata/Dataset/*.*'
    - name: Validate OtherResource json files
      uses: mheap/frontmatter-json-schema-action@main
      with:
        paths: 'metadata/OtherResources/*.*'
